---
title: "`r params$module`"  # Do NOT change this line
subtitle: "`r params$shorttitle`"  # Do NOT change this line
author: "`r params$instructor`"  # Do NOT change this line
date: "`r params$semester`"  # Do NOT change this line
params:
  module: "Name des Moduls"  # Enter HERE the name of the presentation/course/module
  semester: "SoSe 20"   # Enter HERE the date/semester/term
  shorttitle: "Skript"  # Enter HERE a subtitle/shorttitle
  instructor: "Name der Lehrperson"  # ENTER here the presentator's/instructor's name
output:
  xaringan::moon_reader:
    includes:
      after_body: insert-logo.html
    lib_dir: libs
    css: ["footer-header.css", "xafom.css"]
    nature:
      titleSlideClass: [middle, right]
      ratio: "4:3"  # Note that currently only 4:3 format is supported
---


layout: true

<!-- the following lines define the header and the footer line: -->
<div class="my-header"></div>
<div class="my-footer"><span>`r params$semester`    
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
`r params$instructor` | `r params$module` </span></div> 

<div class="footer-line"></div>



<!-- Define an automatic count for header 1/2/exercises -->
```{r echo = FALSE}
h1_count <<- 0

h1 <- function() {
  h1_count <<- h1_count + 1
  return(h1_count)
}


h2_count <<- 0

h2 <- function() {
  h2_count <<- h2_count + 1
  retuern(h2_count)
}

exercise_count <<- 0

ex <- function() {
  exercise_count <<- exercise_count + 1
  retuern(exercise_count)
}
```

---

class: section


# .large[.grey[`r h1()`]] Neuer Abschnitt Ebene 1


---


## Test Level2

.dark[sdakjflsf]

*adsfjkl*

`r h1()`

```{r}
h1()
```


**strong**




---

# Test 3

sdkjfl:

- sdjkfl

- sjfkl





---

class: center, inverse, middle

asdjklfsadf
